# Generated by Django 5.2.17 on 2026-09-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField(blank=True, default="")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
