# Generated by Django 5.2.17 on 2026-09-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("edition_code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=599.0, max_digits=10),
                ),
                ("primary_color", models.CharField(default="#0b0f19", max_length=50)),
                ("accent_color", models.CharField(default="#38bdf8", max_length=50)),
                (
                    "texture_type",
                    models.CharField(default="matte-metallic", max_length=50),
                ),
                (
                    "preview_image",
                    models.ImageField(blank=True, null=True, upload_to="card_designs/"),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "edition",
                    models.CharField(default="Standard Edition", max_length=100),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct or CDN image fallback",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("color_hex", models.CharField(default="#0f172a", max_length=50)),
                ("finish", models.CharField(default="Matte Brushed", max_length=100)),
                ("badge_text", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of feature bullet points",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
