# Generated by Django 5.2.17 on 2026-09-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carddesign",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="carddesign",
            name="edition_code",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="badge_text",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="color_hex",
            field=models.CharField(blank=True, default="#0f172a", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="finish",
            field=models.CharField(blank=True, default="Matte Brushed", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Direct, CDN or local asset path",
                max_length=500,
            ),
        ),
    ]
