# Generated by Django 5.2.17 on 2026-09-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_carddesign_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="back_image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="back_image_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Back side card image URL",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Direct, CDN or local asset path (Front)",
                max_length=500,
            ),
        ),
    ]
