# Generated by Django 5.2.17 on 2026-09-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_back_image_product_back_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="regular_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="1. Regular Price in ৳",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vip_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="2. VIP Price in ৳",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=599.0, max_digits=10),
        ),
    ]
